### ISSUE TITLE
Request to use

### ISSUE THREAD

**Issue by insuusvenerati** [wowdb/api#4]
Hey there! I was looking over this project and it's suits what i'm trying to do perfectly. This combined with wow.tools csv data can help a lot with a project i'm working on.

I was wondering if you'd allow me to use it on a personal, entirely non commercial, project i'm doing mostly for learning purposes.

**Comment by alizahid** [comment]
Hey @insuusvenerati. This project has an [MIT license](https://github.com/wowdb/api/blob/master/license), so feel free to use it!

Out of curiosity, what are you building?

I looked at wow.tools. Looks amazing! Maybe I should get my data from there instead of Blizzard APIs.

**Comment by insuusvenerati** [comment]
Awesome thank you. At the moment I’m scaffolding some basic implementations of React and some API server.  At the moment I’m just pulling a random set of zones as a prompt for artists. I plan on adding more and more as I come up with ideas.

And yes definitely get what you can from wow.tools since the blizzard api doesn’t have much. I was able to get all zones and subs ones from wow.tools in csv and convert it to json.

I liked the idea of using mongodb though and your project gave me the motivation to try it sooner.
